services:
  jupyter:
    image: jupyter/base-notebook
    container_name: jupyter-server
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./:/home/jovyan/
    environment:
      - JUPYTER_ENABLE_LAB=yes
    command: start-notebook.sh --NotebookApp.token='S5Zu7UTkq!eK2f'
    deploy:
      resources:
        limits:
          cpus: "10"
          memory: 24G