

# Created on Tue Mar 12 12:39:57 2019
# @author: sigbjornmne

proj_name:        'iliasgdk_thesis'

#test

#stc_version:      'v001'
#stc_version:      'v002'
#stc_version:      'v003'
#stc_version:      'v004'
#stc_version:      'v005'
#stc_version:      'v006'
#stc_version:      'v007'
#stc_version:      'v008'
#stc_version:      'v009'
#stc_version:      'v010'
#stc_version:      'v011'
# stc_version:      'v015'


#vars/lists
fs:               2000
n_events:         7
n_trials:         10
n_subjects:       12
n_comforts:       5
event_id_list:    [1, 2, 3, 4, 5, 6, 7]
event_name_list:  ['2.8', '16.7', '33.3', '50.0', '66.7', '83.3', '97.2']
comfort_id_list:  [1, 2, 3, 4, 5]
subject_idx_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


#pathss
proj_dir:         '.'
temp_dir:         './scratch/temp'
raw_dir:          './raw'
scratch_dir:      './scratch'
atlas_dir:        './scratch/atlas'
comfort_dir:      './scratch/comfort'
events_dir:       './scratch/events'
fs_subjects_dir:  './scratch/fs_subjects_dir'
fwd_dir:          './scratch/fwd'
harm_dir:         './scratch/harm'
morph_dir:        './scratch/morph'
sn_subjects_dir:  './scratch/sn_subjects_dir'
stc_dir:          './scratch/stc'
trans_dir:        './scratch/trans'
volume_dir:       './scratch/volume'
raw_subset_dir:   './scratch/raw_subset'
scripts_dir:      './scritps'
sensor_dir:       './scratch/sensor' 
epochs_dir:       './scratch/sensor/epochs' 

# proj_dir:         '/Volumes/projects/MINDLAB2018_MEG-Flicker'
# temp_dir:         '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/temp'
# raw_dir:          '/Volumes/projects/MINDLAB2018_MEG-Flicker/raw'
# scratch_dir:      '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch'
# atlas_dir:        '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/atlas'
# comfort_dir:      '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/comfort'
# events_dir:       '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/events'
# fs_subjects_dir:  '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/fs_subjects_dir'
# fwd_dir:          '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/fwd'
# harm_dir:         '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/harm'
# morph_dir:        '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/morph'
# sn_subjects_dir:  '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/sn_subjects_dir'
# stc_dir:          '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/stc'
# trans_dir:        '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/trans'
# volume_dir:       '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/volume'
# raw_subset_dir:   '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/raw_subset'
# scripts_dir:      '/Volumes/projects/MINDLAB2018_MEG-Flicker/scritps'
# sensor_dir:       '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/sensor' 
# epochs_dir:       '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/sensor/epochs' 






#morph_img_dir:    '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/morph_img'   

# del
#stc_subject_dir:  '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/stc/subject'
#stc_group_dir:    '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/stc/group'
#sensor_analysis_dir:       '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/sensor_analysis' 
#source_analysis_dir:       '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/source_analysis' 
#group_dir:        '/Volumes/projects/MINDLAB2018_MEG-Flicker/scratch/group'


#%% for local processing
#fs_subjects_L_dir:  '/Volumes/KINGSTON/cfin_flicker/scratch/fs_subjects_dir'
#scratch_L_dir:      '/Volumes/KINGSTON/scratch_L'
#stc_L_dir:          '/Volumes/KINGSTON/scratch_L/stc'
#morph_L_dir:        '/Volumes/KINGSTON/scratch_L/morph'  
#fwd_L_dir:          '/Volumes/KINGSTON/scratch_L/fwd'
#volume_L_dir:       '/Volumes/KINGSTON/scratch_L/volume'
#harm_L_dir:         '/Volumes/KINGSTON/scratch_L/harm'
#atlas_L_dir:        '/Volumes/KINGSTON/scratch_L/atlas'
#group_L_dir:        '/Volumes/KINGSTON/scratch_L/group'
#morph_img_L_dir:    '/Volumes/KINGSTON/scratch_L/morph_img'
#gfx_L_dir:          '/Volumes/KINGSTON/scratch_L/gfx'
#comfort_L_dir:        '/Volumes/KINGSTON/scratch_L/comfort'




#subject_nrs:      ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12']
subject_nr_list:  ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8', 's9', 's10', 's11', 's12']

#subject_ids:      ['0005_3SJ', '0002_TCZ', '0009_YGZ', '0010_ZMG', '0011_MEE',
#                  '0012_C3Z', '0014_TAG', '0015_QKW', '0016_XLZ', '0017_QJ5',
#                  '0018_5T3', '0019_COG']
                  
subject_id_list:  ['0005_3SJ', '0002_TCZ', '0009_YGZ', '0010_ZMG', '0011_MEE',
                  '0012_C3Z', '0014_TAG', '0015_QKW', '0016_XLZ', '0017_QJ5',
                  '0018_5T3', '0019_COG']

#raw_paths1:       ['0005/20180514_000000/MEG/001.flicker/files/flicker.fif', 
#                  '0002/20180522_000000/MEG/001.s2/files/s2.fif', 
#                  '0009/20180522_000000/MEG/001.s3p1/files/s3p1.fif', 
#                  '0010/20180523_000000/MEG/001.s4/files/s4.fif', 
#                  '0011/20180524_000000/MEG/001.s5/files/s5.fif', 
#                  '0012/20180524_000000/MEG/001.s6/files/s6.fif', 
#                  '0014/20180525_000000/MEG/001.s7/files/s7.fif', 
#                  '0015/20180525_000000/MEG/001.s8/files/s8.fif', 
#                  '0016/20180525_000000/MEG/001.s9p1/files/s9p1.fif', 
#                  '0017/20180530_000000/MEG/001.s10/files/s10.fif',
#                  '0018/20180530_000000/MEG/001.s11/files/s11.fif', 
#                  '0019/20180530_000000/MEG/001.s12/files/s12.fif']

raw_path1_list:   ['0005/20180514_000000/MEG/001.flicker/files/flicker.fif', 
                  '0002/20180522_000000/MEG/001.s2/files/s2.fif', 
                  '0009/20180522_000000/MEG/001.s3p1/files/s3p1.fif', 
                  '0010/20180523_000000/MEG/001.s4/files/s4.fif', 
                  '0011/20180524_000000/MEG/001.s5/files/s5.fif', 
                  '0012/20180524_000000/MEG/001.s6/files/s6.fif', 
                  '0014/20180525_000000/MEG/001.s7/files/s7.fif', 
                  '0015/20180525_000000/MEG/001.s8/files/s8.fif', 
                  '0016/20180525_000000/MEG/001.s9p1/files/s9p1.fif', 
                  '0017/20180530_000000/MEG/001.s10/files/s10.fif',
                  '0018/20180530_000000/MEG/001.s11/files/s11.fif', 
                  '0019/20180530_000000/MEG/001.s12/files/s12.fif']
#                  
#raw_paths2:       ['', 
#                  '', 
#                  '0009/20180522_000000/MEG/002.s3p2/files/s3p2.fif', 
#                  '', 
#                  '', 
#                  '', 
#                  '', 
#                  '', 
#                  '0016/20180525_000000/MEG/002.s9p2/files/s9p2.fif', 
#                  '', 
#                  '', 
#                  '']
                  
raw_path2_list:   ['', 
                  '', 
                  '0009/20180522_000000/MEG/002.s3p2/files/s3p2.fif', 
                  '', 
                  '', 
                  '', 
                  '', 
                  '', 
                  '0016/20180525_000000/MEG/002.s9p2/files/s9p2.fif', 
                  '', 
                  '', 
                  '']
                  
bads:             ['MEG1143']
# Possibly bad : 'MEG0121'